enum CreateSendSegmentRuleErrorCode {
    EmptySegmentSubject = 2700,
    InvalidSegmentSubject = 2701,
    EmptySegmentClauses = 2702,
    EmptySegmentClause = 2706,
    InvalidSegmentClauses = 2703,
    InvalidSegmentClause = 2707,
    EmptySegmentRuleType = 2704,
    InvalidSegmentRuleType = 2705,
}

enum CreateSendSegmentClauseErrorCode {
    EmptyClause = 2710,
    SegmentRuleClauseUnparsed = 2711,
    InvalidVerbForNameRule = 2712,
    InvalidVerbForEmailRule = 2713,
    InvalidVerbForDateSubscribedRule = 2714,
    InvalidVerbForTextFieldRule = 2715,
    InvalidVerbForNumberFieldRule = 2716,
    InvalidVerbForMultiOptionFieldRule = 2717,
    InvalidVerbForDateFieldRule = 2718,
    RequiredClauseObjectMissing = 2719,
    InvalidDateFormat = 2720,
    InvalidNumberFormat = 2721,
    OptionDoesntExistForField = 2722,
    InvalidYearForDateSubscribed = 2723,
    ValidCampaignIdRequired = 2750,
    CampaignNotSentToList = 2751,
    WorkflowNotSentToList = 2752,
    LinkNotInCampaign = 2753,
    SegmentRuleClauseNotParsed = 2754,
    InvalidBetweenDateFormat = 2755,
    InvalidBetweenNumberFormat = 2756,
    InvalidVerbForLocationRule = 2757,
    InvalidOperandForLocationRule = 2758,
    ValidWorkflowEmailIdRequired = 2759,
    LinkNotInWorkflowEmail = 2760,
    InvalidOperandForEngagmentSegmentRule = 2761,
}

enum CreateSendCssProcessingError {
    InvalidBaseUrl = 8000,
    CssInlinerHtmlContentLimitExceeded = 8001,
}

enum CreateSendTemplateErrorCode {
    InvalidTemplateId = 4001,
    InvalidTemplateName = 4003,
}

enum CreateSendTemplateValidationErrorCode {
    NoDescriptionsOrRepeater = 4101,
    NoClosingRepeater = 4102,
    NoWidthSpecifiedInTheImageTag = 4103,
    NoTitleDescriptionOrImageInARepeaterTag = 4104,
    NoClosingTableofcontents = 4108,
    NoRepeaterTitleTag = 4109,
    RepeaterTitleTagWithoutOpenTableOfContentsTag = 4110,
    RepeaterTitleTagWithoutOpenOrCloseTableOfContentsTag = 4111,
    TableofcontentsWithNoRepeaterTag = 4118,
    NoWidthSpecifiedForTheImageTagThatTheImageSrcIsIn = 4119,
    RepeaterContainsMoreThanOneTitleTag = 4120,
    RepeaterContainsMoreThanOneDescriptionTag = 4121,
    ContainsMultipleRepeaterTags = 4123,
    NonRepeaterImageNoWidth = 4124,
    LinkInUnsubscribeTags = 4125,
    ClosingRepeaterTagFoundBeforeTheOpenRepeaterTag = 4126,
    MultipleTocTrueRepeaters = 4127,
    NestedRepeaters = 4128,
    TableBasedRepeaterContainsMultipleTrs = 4129,
    ContainsFlash = 4201,
    ContainsScript = 4202,
    ContainsJava = 4203,
    NoUnsubscribeTag = 4300,
    UnsubscribeTagHiddenInComments = 4301,
    UnsubscribeTagContainsLessThan3Chars = 4302,
    UnsubscribeTagContainsALink = 4303,
    NoClosingUnsubscribeTag = 4304,
    UnsubscribeInsideCampMonTag = 4306,
    UnsubscribeInsideLink = 4307,
    FilesMissingFromArchive = 4350,
}

enum CreateSendWorkflowErrorCode {
    InvalidWorkflowId = 3000,
    BadActionId = 3001,
    InvalidWorkflowEmailId = 3002,
    InvalidJourneyName = 3003,
}

enum CreateSendErrorCode {
    // Generic
    Success = 0,
    InvalidEmail = 1,
    InvalidDate = 5,
    InvalidAuthorizationHeader = 50,
    InvalidForNonAgency = 51,
    PermissionDenied = 60,
    InvalidApiKey = 100,
    InvalidListId = 101,
    InvalidClientId = 102,
    EmptyApiKey = 103,
    InvalidLogin = 105,
    OperationNotPermitted = 106,
    InvalidLoginUrl = 107,
    TooManyAttempts = 108,
    DeprecatedMethod = 110,
    MethodUnavailableToFreeAccounts = 111,
    InvalidOAuthToken = 120,
    ExpiredOAuthToken = 121,
    RevokedOAuthToken = 122,
    RestrictedTokenMethodFailure = 123,
    InvalidAuthenticationMethod = 124,
    InvalidDestinationClientId = 125,
    InvalidDestinationListId = 126,

    GenericInvalidFromDateFormat = 920,
    GenericInvalidDateRange = 921,
    GenericInvalidToDateFormat = 922,
    GenericInvalidTimeZoneFormat = 923,
    SmartAndGroupedConflict = 924,
    InvalidSmartEmailId = 925,
    SmartEmailNotFound = 926,
    GenericInvalidDateRangeToDateExclusive = 927,

    BadCampaignId = 301,
    BadMessageId = 302,

    // Paging errors
    InvalidPageNumber = 800,
    InvalidPageSize = 801,
    InvalidPagingSortField = 802,
    InvalidPagingSortOrder = 803,
    InvalidCustomFieldSize = 810,
    DatabaseError = 900,
    UndefinedError = 1000,

    // Clients
    EmailTaken = 150,
    UserNameTaken = 151,
    InvalidTimeZone = 152,
    InvalidAccessLevel = 153,
    EmptyCompanyName = 154,
    EmptyContactName = 155,
    InvalidCountry = 157,
    EmptyUserName = 158,
    InvalidPasswordLegacy = 159,
    InvalidBillingType = 160,
    DeliveryFeeRequired = 161,
    CostPerRecipientRequired = 162,
    DesignAndSpamTestFeeRequired = 163,
    InvalidDeliveryFee = 164,
    InvalidCostPerRecipient = 165,
    InvalidDesignAndSpamTestFee = 166,
    InvalidCurrency = 167,
    DeliveryFeeBelowMinimum = 168,
    CostPerRecipientBelowMinimum = 169,
    MarkupRateTooLow = 170,
    DesignAndSpamTestFeeBelowMinimum = 171,
    ClientAddFromApiLimitExceeded = 172,
    CannotSetBillingWithoutAccess = 173,
    EmailAddressNotInSuppressionList = 176,
    AttemptToTransferGreaterThanTotalClientCredits = 177,
    AttemptToTransferGreaterThanTotalAccountCredits = 178,

    // Authentication
    UnsafePassword = 174,
    InvalidPassword = 175,
    WeakPassword = 179,
    InvalidStrongPassword = 180,
    LongPassword = 181,
    ElevatedRequired = 182,
    TwoFactorCodeIncorrect = 183,
    TwoFactorCodeVerificationError = 184,

    // Subscribers
    InSuppressionList = 204,
    InDeleted = 205,
    InUnsubscribed = 206,
    InBounced = 207,
    InUnconfirmed = 208,
    TooManySubscribersInBatch = 209,
    BatchContainsFailures = 210,
    NoSubscribersInBatch = 212,
    MustProvideConsentToTrackValue = 213,
    InvalidMobileNumber = 220,
    InvalidEmailAndMobileNumber = 221,
    InvalidConsentToSendSmsValue = 222,

    // Lists
    DuplicateListTitle = 250,
    ListTitleEmpty = 251,
    ListHasCampaigns = 252,
    InvalidPersonalisationTag = 253,
    InvalidFieldName = 254,
    FieldKeyExists = 255,
    OptionsForTextOrNumber = 256,
    NoOptionsForMultiValuedField = 257,
    InvalidVisibleInPreferenceCentre = 258,
    InvalidDataType = 259,
    TooManyCustomFields = 260,
    InvalidListUnsubscribeSetting = 261,
    UnableToUpdateAllContactsList = 262,
    CustomFieldUsedInAWorkflow = 263,
    CustomFieldOptionUsedInAWorkflow = 264,
    SegmentUsedInAWorkflow = 265,
    ListUsedInASegmentRule = 266,
    ListCustomFieldUsedInASegmentRule = 267,
    ListUsedByCommerceIntegration = 268,

    // Segments
    InvalidSegmentId = 271,
    SegmentHasCampaigns = 272,
    SegmentTitleEmpty = 273,
    DuplicateSegmentTitle = 275,
    InvalidSegmentRules = 277,
    SegmentCalculationInProgress = 278,
    SegmentNotFound = 279,
    SegmentStructureNotSupported = 280,
    SegmentMigrationInProgress = 281,
    InvalidSegmentPayload = 282,
    MaximumNumberOfRulesReached = 283,
    UneditableSegment = 284,
    EngagementSegmentRuleGroupHasOtherRuleTypes = 285,
    EngagementSegmentRulesNotAvailable = 286,
    SegmentTemporarilyUnavailable = 287,

    // Create Campaign
    DuplicateCampaignName = 303,
    SubjectRequired = 304,
    FromNameRequired = 305,
    InvalidFromAddress = 307,
    ReplyToRequired = 308,
    InvalidReplyTo = 309,
    HtmlRequired = 310,
    InvalidHtmlContent = 311,
    InvalidTextUrl = 312,
    InvalidListIds = 313,
    InvalidSegments = 314,
    ListsOrSegmentsRequired = 315,
    ProblemsImportingLinks = 316,
    LinkTooLong = 317,
    TextUnsubscribeTagInHtmlEmail = 318,
    CampaignNameRequired = 319,
    TemplateContentRequired = 320,
    TemplateContentIncludesInvalidImageUrl = 321,
    FromNameReservedKeywordError = 322,
    FromAddressFallbackError = 323,
    FromAddressReservedKeywordError = 324,
    ReplyToFallbackError = 325,
    ReplyToReservedKeywordError = 326,

    // Send campaign
    CampaignAlreadySent = 331,
    NoRecipientsAdded = 332,
    NoTestCampaignsAvailable = 333,
    PendingApproval = 334,
    PaymentDetailsRequired = 335,
    CampaignPaymentFailed = 336,
    InvalidDeliveryDate = 337,
    ConfirmEmailRequired = 338,
    ConfirmEmailInvalid = 339,
    ListsAddedContainNoRecipients = 340,
    CampaignNotScheduled = 341,
    RequiresJustification = 344,
    MonthlyPaymentFailed = 355,

    // Send campaign preview
    NoPreviewRecipientsSupplied = 370,
    InvalidPreviewRecipientEmails = 371,
    RecipientNotInCampaignLists = 373,
    TooManyPreviewRecipients = 374,
    ClientTestCampaignRateViolation = 375,
    CampaignMustHaveContentAndRecipients = 376,

    BadRequest = 400,
    Gone = 410,
    InternalServerError = 500,

    // Webhooks
    InvalidWebhookUrl = 601,
    InvalidWebhookFormat = 602,
    InvalidWebhookEvent = 603,
    InvalidWebhookId = 604,
    WebhookRequestFailed = 610,
    WebhookDoesNotExist = 699,

    // People
    EmptyPersonName = 701,
    PersonNotFound = 702,
    CannotDeleteLastPerson = 703,
    PersonNotActive = 704,

    // Pricing
    InvalidMonthlyScheme = 720,

    // Admins
    EmptyAdminName = 751,
    AdminNotFound = 752,
    CannotDeleteLastAdmin = 753,
    AdminNotActive = 754,

    // Iframe session
    UnknownMember = 5001,
    InvalidIntegratorId = 5002,
    InvalidChrome = 5003,
    InvalidRedirectUrl = 5004,

    ProblemWithYourAccount = 700,
    IpWhitelistCheckFailure = 666,

    // Timeline
    InvalidCount = 850,

    InvalidClicks = 933,
    InvalidOpens = 934,
    InvalidStatistics = 935,
    InvalidDataProperty = 991,
    InvalidDataValue = 992,
    RecipientRequired = 952,
    TooManyTransactionalRecipients = 954,
    InvalidRecipientAddress = 953,
    InvalidSentBeforeId = 904,
    InvalidSentAfterId = 905,

    AttachmentNameRequired = 981,
    AttachmentTypeRequired = 982,
    InvalidAttachmentType = 983,
    InvalidAttachmentContent = 984,

    InvalidTrackClick = 970,
    InvalidTrackOpen = 971,
    InvalidInlineCss = 972,
    InvalidConsentToTrackValue = 974,
    MustContainHtmlOrText = 960,
    InvalidTransactionalReplyToAddress = 955,
    TooLongTransactionalReplyToAddress = 956,
    InvalidTransactionalSenderAddress = 957,
    TooLongTransactionalSenderAddress = 958,
    InvalidTransactionalQueryStatus = 932,
    InvalidAddRecipientsToList = 973,
    ItemNotFound = 404,
    TransactionalStopped = 990,
    TransactionalRequiresMonthlyPlan = 980,
    TransactionalNoDkim = 993,
    TransactionalInvalidSenderDomain = 994,
    InvalidJson = 995,
    EmailVariableSizeExceeded = 996,
}

export {
    CreateSendSegmentRuleErrorCode,
    CreateSendSegmentClauseErrorCode,
    CreateSendCssProcessingError,
    CreateSendTemplateErrorCode,
    CreateSendTemplateValidationErrorCode,
    CreateSendWorkflowErrorCode,
    CreateSendErrorCode,
};
